import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hulu-Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://e7.pngegg.com/pngimages/647/457/png-clipart-logo-computer-icons-hulu-television-show-logo-letter-font-p-television-angle-thumbnail.png" />
      </Head>

     
    </div>
  )
}
