import Head from 'next/head'
import Image from 'next/image'
import { Header } from '../Components/Header'

export default function Home() {
  return (
    <div className='bg-gray-7
    00 '>
      <Head>
        <title>Hulu-Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://cdn4.iconfinder.com/data/icons/logos-brands-5/24/hulu-512.png" />
      </Head>
    {/* Header  */}
    <Header/>
    {/* Navigation  */}
    {/* Main contents */}
     
    </div>
  )
}
