import Head from 'next/head'
import Image from 'next/image'
import { Header } from '../Components/Header'
import MainContent from '../Components/MainContent'
import Nav from '../Components/Nav'
import Requestdata from '../utils/Requestdata'

export default function Home(props) {
 // console.log(data);
  return (
    <div className=''>
      <Head>
        <title>Hulu-Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://cdn4.iconfinder.com/data/icons/logos-brands-5/24/hulu-512.png" />
      </Head>
    {/* Header  */}
       <Header/>
    {/* Navigation  */}
        <Nav/>
    {/* Main contents */}
     <MainContent requestData={props.data}/>
     
    </div>
  )
}


export async function getServerSideProps(context) {
  const query = context.query.genre
  const res = await fetch(`https://api.themoviedb.org/3${Requestdata[query]?.url || Requestdata.fetchTrending.url}`)
  const data = await res.json()
  if (!data) {
    return {
      notFound: true,
    }
  }

  return {
    props: {data:data.results}, // will be passed to the page component as props
  }
}